In [1]:
import numpy as np

In [2]:
A = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
B = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [9]:
x=np.dot(A,B)
x

array([[[[  7,  10],
         [ 19,  22]],

        [[ 15,  22],
         [ 43,  50]]],


       [[[ 23,  34],
         [ 67,  78]],

        [[ 31,  46],
         [ 91, 106]]]])

In [10]:
np.matmul(A,B)

array([[[  7,  10],
        [ 15,  22]],

       [[ 67,  78],
        [ 91, 106]]])

In [11]:
A@B

array([[[  7,  10],
        [ 15,  22]],

       [[ 67,  78],
        [ 91, 106]]])

In [13]:
x.shape

(2, 2, 2, 2)