In [38]:
import numpy as np
from sklearn.datasets import load_wine
from sklearn.svm import SVC,LinearSVC
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.preprocessing import StandardScaler

In [39]:
df=load_wine()

In [40]:
print(df)

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

In [41]:
data=df['data']
target=df['target']
np.unique(target)

array([0, 1, 2])

In [42]:
def my_kernel(X,Y):
    return np.dot(X,Y.T)

In [43]:
x_train,x_test,y_train,y_test=train_test_split(data,target,test_size=0.2,random_state=42,shuffle=True,stratify=target)

In [50]:
p1=make_pipeline(StandardScaler(),SVC(kernel='linear'))
p2=make_pipeline(StandardScaler(),SVC(kernel='precomputed'))
gram_train=np.dot(x_train,x_train.T)
gram_test=np.dot(x_test,x_train.T)
p3=make_pipeline(StandardScaler(),SVC(kernel=my_kernel))
p4=make_pipeline(StandardScaler(),LinearSVC())

In [51]:
p1.fit(x_train,y_train)
p2.fit(gram_train,y_train)
p3.fit(x_train,y_train)
p4.fit(x_train,y_train)

C:\Users\sudip\PycharmProjects\pythonProject\venv\lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


Pipeline(steps=[('standardscaler', StandardScaler()),
                ('linearsvc', LinearSVC())])

# Using SVC with Linear Kernel

In [52]:
y_pred1=p1.predict(x_test)
print(accuracy_score(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))
print(classification_report(y_test,y_pred1))

0.9444444444444444
[[12  0  0]
 [ 1 13  0]
 [ 0  1  9]]
              precision    recall  f1-score   support

           0       0.92      1.00      0.96        12
           1       0.93      0.93      0.93        14
           2       1.00      0.90      0.95        10

    accuracy                           0.94        36
   macro avg       0.95      0.94      0.95        36
weighted avg       0.95      0.94      0.94        36



# Implementing Linear Kernel using Gram Matrix

In [53]:
y_pred2=p2.predict(gram_test)
print(accuracy_score(y_test,y_pred2))
print(confusion_matrix(y_test,y_pred2))
print(classification_report(y_test,y_pred2))

0.3888888888888889
[[ 0 12  0]
 [ 0 14  0]
 [ 0 10  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        12
           1       0.39      1.00      0.56        14
           2       0.00      0.00      0.00        10

    accuracy                           0.39        36
   macro avg       0.13      0.33      0.19        36
weighted avg       0.15      0.39      0.22        36



C:\Users\sudip\PycharmProjects\pythonProject\venv\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sudip\PycharmProjects\pythonProject\venv\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sudip\PycharmProjects\pythonProject\venv\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_

# Implementing Linear Kernel using function

In [54]:
y_pred3=p3.predict(x_test)
print(accuracy_score(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))
print(classification_report(y_test,y_pred3))

0.9444444444444444
[[12  0  0]
 [ 1 13  0]
 [ 0  1  9]]
              precision    recall  f1-score   support

           0       0.92      1.00      0.96        12
           1       0.93      0.93      0.93        14
           2       1.00      0.90      0.95        10

    accuracy                           0.94        36
   macro avg       0.95      0.94      0.95        36
weighted avg       0.95      0.94      0.94        36



# Implementing Linear SVC

In [55]:
y_pred4=p4.predict(x_test)
print(accuracy_score(y_test,y_pred4))
print(confusion_matrix(y_test,y_pred4))
print(classification_report(y_test,y_pred4))

0.9722222222222222
[[12  0  0]
 [ 0 14  0]
 [ 0  1  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.93      1.00      0.97        14
           2       1.00      0.90      0.95        10

    accuracy                           0.97        36
   macro avg       0.98      0.97      0.97        36
weighted avg       0.97      0.97      0.97        36



In [61]:
def is_positive_semi_definite(matrix):
    eigenvalues = np.linalg.eigvals(matrix)
    return np.all(eigenvalues >= 0)

In [90]:
def check_kernel(kernel_func, points):
    """
    Check if the given kernel function is positive semi-definite for a set of points.
    
    Args:
    - kernel_func: A function K(a, b) that takes two arguments and returns a scalar.
    - points: A list of points to construct the kernel matrix.
    
    Returns:
    - True if the kernel function is positive semi-definite for the given points, False otherwise.
    """       
    kernel_matrix=np.array(kernel_func(points,points))
    print(kernel_matrix)
    if is_positive_semi_definite(kernel_matrix) and np.all(kernel_matrix==kernel_matrix.T):
        return True
    else:
        return False

# Example kernel function
def example_kernel(a, b):
    return np.sin(np.power(np.dot(a.T,b),2))

# Example usage
points = np.array([[0, np.pi/3], [np.pi/4, np.pi/6]])
is_kernel = check_kernel(example_kernel, points)
print("Is the example kernel valid?", is_kernel)

[[0.37138871 0.16830807]
 [0.16830807 0.95286989]]
Is the example kernel valid? True
