In [3]:
import numpy as np
from sklearn.datasets import load_digits,load_iris
from sklearn.semi_supervised import SelfTrainingClassifier
from sklearn.ensemble import RandomForestClassifier

In [4]:
df1=load_iris()
data1=df1['data']

In [5]:
print(data1)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [6]:
from sklearn.cluster import KMeans

In [8]:
kmeans=KMeans(n_clusters=3,random_state=42)
kmeans.fit(data1)

C:\Users\sudip\PycharmProjects\pythonProject\venv\lib\site-packages\sklearn\cluster\_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


KMeans(n_clusters=3, random_state=42)

In [9]:
kmeans.labels_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0])

In [10]:
target1=df1['target']

In [13]:
mismatch=np.sum(target1!=kmeans.labels_)    

In [14]:
print(mismatch)

114


In [15]:
print(len(target1),len(kmeans.labels_))

150 150


In [16]:
print(target1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [18]:
def interchange(arr):
    ones=arr==1
    zeros=arr==0
    arr[ones]=0
    arr[zeros]=1
    return arr

In [19]:
l1=interchange(kmeans.labels_)

In [20]:
mismatch=np.sum(target1!=kmeans.labels_)    

In [21]:
print(mismatch)

16


# Semi-Supervised Learning using Self-Training Classifier

In [41]:
kmeans_data=kmeans.transform(data1)
from sklearn.model_selection import train_test_split
def get_samples_evenly_from_each_cluster(total,data,clusters,k,n_samples=10):
    indices=np.arange(data.shape[0])
    _,samples,_,_,_,test_idx=train_test_split(data1,clusters,indices,test_size=n_samples/total,stratify=clusters,random_state=42)
    return samples,test_idx

In [42]:
tolabel_data,tolabel_idx=get_samples_evenly_from_each_cluster(150,kmeans_data,kmeans.labels_,3,10)

In [43]:
print(tolabel_data)
print(tolabel_idx)

[[6.8 2.8 4.8 1.4]
 [5.8 4.  1.2 0.2]
 [5.2 3.4 1.4 0.2]
 [6.3 2.8 5.1 1.5]
 [4.4 3.  1.3 0.2]
 [6.3 2.9 5.6 1.8]
 [6.9 3.1 5.1 2.3]
 [7.7 3.  6.1 2.3]
 [5.2 2.7 3.9 1.4]
 [6.  2.2 5.  1.5]]
[ 76  14  28 133  38 103 141 135  59 119]


In [44]:
labelled=target1[tolabel_idx]
print(labelled)

[1 0 0 2 0 2 2 2 1 2]


In [46]:
x_train=data1
y_train = np.array([target1[i] if i in tolabel_idx else -1 for i in range(len(target1))])

In [47]:
print(y_train)

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1  2 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  2
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  2 -1  2 -1 -1 -1 -1 -1  2 -1 -1
 -1 -1 -1 -1 -1 -1]


In [49]:
base_classifier = RandomForestClassifier()
self_training_model = SelfTrainingClassifier(base_classifier)
self_training_model.fit(x_train, y_train)

SelfTrainingClassifier(base_estimator=RandomForestClassifier())

In [51]:
predictions = self_training_model.predict(x_train)

In [52]:
print(predictions)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1
 1 1 1 2 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 1 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2
 2 2]


# Just for showing(not to be used in actual semi-supervised learning)

In [54]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(target1,predictions))
print(confusion_matrix(target1,predictions))
print(classification_report(target1,predictions))

0.9533333333333334
[[50  0  0]
 [ 0 46  4]
 [ 0  3 47]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.94      0.92      0.93        50
           2       0.92      0.94      0.93        50

    accuracy                           0.95       150
   macro avg       0.95      0.95      0.95       150
weighted avg       0.95      0.95      0.95       150

